import { AppText } from "@/components/app-text";
import { AppIcon } from "@/components/app-icon";
import { router } from 'expo-router';
import { Pressable, StyleSheet, View } from 'react-native';
import { BottomBar, C, Header, Page, SectionTitle, Surface } from '@/components/app-ui';
import { getDemoUser, resetDemoUser } from '@/data/demo-session';
const rows=[['group','Mon cercle d’amis','Créer un groupe et inviter tes proches','/circles'],['♙','Mon compte','Nom, e-mail et pays','/account'],['shield','Sécurité du compte','Mot de passe, double authentification et sessions','/security'],['♡','Voyages enregistrés','Tes idées pour plus tard','/my-trips'],['◈','Langue et devise','Français · XOF (FCFA)','/settings'],['?','Centre d’aide','Questions et assistance','/settings']];
export default function Profile(){const user=getDemoUser();return <View style={{flex:1,backgroundColor:C.cream}}><Page><Header title="Mon profil" right={<Pressable onPress={()=>router.push('/settings')}><AppIcon name="settings" size={19} /></Pressable>}/><AppText style={st.greeting}>Salut, {user.firstName}</AppText><AppText style={st.sub}>Voyageuse depuis 2024 · Profil de démonstration</AppText><Surface style={st.profile}><View style={st.avatar}><AppText style={{fontSize:25,fontWeight:'900',color:C.green}}>{user.firstName.charAt(0).toUpperCase()}</AppText></View><View style={{flex:1}}><AppText style={st.name}>{user.firstName} {user.lastName}</AppText><AppText style={st.sub}>{user.email}</AppText><AppText style={st.sub}>{user.country}</AppText></View><Pressable onPress={()=>router.push('/account')}><AppText style={st.link}>Modifier ›</AppText></Pressable></Surface><SectionTitle title="Ton année en voyages"/><View style={st.stats}>{[['3','voyages'],['8','villes'],['13','amis']].map(([num,label])=><View key={label} style={{alignItems:'center',gap:4}}><AppText style={st.statNum}>{num}</AppText><AppText style={st.sub}>{label}</AppText></View>)}</View><SectionTitle title="Préférences et compte"/>{rows.map(([icon,title,sub])=><Pressable key={title} onPress={()=>router.push((rows.find((item)=>item[1]===title)?.[3] ?? '/settings') as any)}><Surface style={st.row}><View style={st.icon}><AppIcon name={icon} size={19} color={C.green} /></View><View style={{flex:1}}><AppText style={st.rowTitle}>{title}</AppText><AppText style={st.sub}>{sub}</AppText></View><AppText style={{color:'#A0AAA1'}}>›</AppText></Surface></Pressable>)}<Pressable style={st.logout} onPress={()=>{resetDemoUser();router.replace('/onboarding');}}><AppText style={{fontSize:12,color:'#AE6B59',fontWeight:'800'}}>Recommencer la démo</AppText></Pressable><AppText style={st.foot}>Amivoy · aperçu démo · version 1.0</AppText></Page><BottomBar active="profile"/></View>}
const st=StyleSheet.create({gear:{fontSize:18,color:C.green},greeting:{fontSize:28,fontWeight:'900',color:C.ink},sub:{fontSize:11,color:C.muted,marginTop:4},profile:{flexDirection:'row',alignItems:'center',gap:13},avatar:{width:51,height:51,borderRadius:18,backgroundColor:'#DDE8D4',alignItems:'center',justifyContent:'center'},name:{fontSize:15,fontWeight:'900',color:C.ink,marginBottom:2},link:{color:C.green,fontSize:10,fontWeight:'900'},stats:{flexDirection:'row',justifyContent:'space-around',backgroundColor:C.white,borderRadius:18,padding:16},statNum:{fontSize:22,fontWeight:'900',color:C.green},row:{flexDirection:'row',alignItems:'center',gap:11,padding:12},icon:{width:38,height:38,borderRadius:13,backgroundColor:'#F1F4EB',alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:12,fontWeight:'800',color:C.ink,marginBottom:3},logout:{alignItems:'center',padding:12},foot:{textAlign:'center',fontSize:9,color:'#A0AAA1'}});
