import { SymbolView, type AndroidSymbol, type SFSymbol } from 'expo-symbols';
import { StyleSheet, View } from 'react-native';

type IconDefinition = { ios: string; material: string };
const icons: Record<string, IconDefinition> = {
  globe: { ios: 'globe.americas.fill', material: 'public' }, camera: { ios: 'camera.fill', material: 'photo_camera' }, payments: { ios: 'creditcard.fill', material: 'payments' }, shield: { ios: 'shield.lefthalf.filled', material: 'shield' }, receipt_long: { ios: 'receipt.fill', material: 'receipt_long' }, lightbulb: { ios: 'lightbulb.fill', material: 'lightbulb' }, lock: { ios: 'lock.fill', material: 'lock' }, '📖': { ios: 'book.closed.fill', material: 'menu_book' }, '✨': { ios: 'sparkles', material: 'auto_awesome' }, '🌇': { ios: 'building.2.fill', material: 'location_city' },
  '🇧🇯': { ios: 'globe.americas.fill', material: 'public' }, '🇹🇬': { ios: 'globe.americas.fill', material: 'public' }, '🇬🇭': { ios: 'globe.americas.fill', material: 'public' }, '🇸🇳': { ios: 'globe.americas.fill', material: 'public' }, '🇨🇮': { ios: 'globe.americas.fill', material: 'public' }, '🇲🇦': { ios: 'globe.americas.fill', material: 'public' }, '🇰🇪': { ios: 'globe.americas.fill', material: 'public' }, '🇷🇼': { ios: 'globe.americas.fill', material: 'public' }, '🇿🇦': { ios: 'globe.americas.fill', material: 'public' },
  home: { ios: 'house.fill', material: 'home' }, '⌂': { ios: 'house.fill', material: 'home' },
  trip: { ios: 'suitcase.rolling.fill', material: 'luggage' }, '🧳': { ios: 'suitcase.rolling.fill', material: 'luggage' }, '✈': { ios: 'airplane', material: 'flight' },
  outing: { ios: 'party.popper.fill', material: 'celebration' }, '🎉': { ios: 'party.popper.fill', material: 'celebration' },
  pin: { ios: 'mappin.and.ellipse', material: 'location_on' }, '📍': { ios: 'mappin.and.ellipse', material: 'location_on' }, '⌖': { ios: 'scope', material: 'my_location' },
  apartment: { ios: 'building.2.fill', material: 'apartment' }, '🏠': { ios: 'house.fill', material: 'home' }, '🏢': { ios: 'building.2.fill', material: 'apartment' }, '🏡': { ios: 'house.lodge.fill', material: 'cottage' }, '🏛️': { ios: 'building.columns.fill', material: 'account_balance' }, '🛏️': { ios: 'bed.double.fill', material: 'bed' }, '🌴': { ios: 'tree.palm.fill', material: 'park' },
  restaurant: { ios: 'fork.knife', material: 'restaurant' }, '🍽️': { ios: 'fork.knife', material: 'restaurant' }, '🍲': { ios: 'fork.knife', material: 'soup_kitchen' }, '🥘': { ios: 'fork.knife', material: 'local_dining' }, coffee: { ios: 'cup.and.saucer.fill', material: 'local_cafe' }, '☕': { ios: 'cup.and.saucer.fill', material: 'local_cafe' },
  culture: { ios: 'building.columns.fill', material: 'museum' }, '📚': { ios: 'books.vertical.fill', material: 'menu_book' }, '🕌': { ios: 'building.columns.fill', material: 'mosque' },
  nature: { ios: 'leaf.fill', material: 'eco' }, '🌿': { ios: 'leaf.fill', material: 'eco' }, beach: { ios: 'beach.umbrella.fill', material: 'beach_access' }, '🏝️': { ios: 'beach.umbrella.fill', material: 'beach_access' }, '🌊': { ios: 'water.waves', material: 'water' }, '🛶': { ios: 'sailboat.fill', material: 'kayaking' }, '🌋': { ios: 'mountain.2.fill', material: 'landscape' }, '⛰️': { ios: 'mountain.2.fill', material: 'landscape' },
  city: { ios: 'building.2.fill', material: 'location_city' }, '🌆': { ios: 'building.2.fill', material: 'location_city' }, '🏘️': { ios: 'house.fill', material: 'location_city' }, '🏰': { ios: 'building.columns.fill', material: 'castle' }, '🏺': { ios: 'building.columns.fill', material: 'museum' }, '🎨': { ios: 'paintpalette.fill', material: 'palette' }, '🧿': { ios: 'sparkles', material: 'auto_awesome' }, '🦒': { ios: 'pawprint.fill', material: 'pets' },
  boat: { ios: 'sailboat.fill', material: 'directions_boat' }, market: { ios: 'basket.fill', material: 'storefront' }, '🧺': { ios: 'basket.fill', material: 'shopping_basket' }, '🧵': { ios: 'scissors', material: 'checkroom' }, '🍋': { ios: 'carrot.fill', material: 'nutrition' }, '🥐': { ios: 'takeoutbag.and.cup.and.straw.fill', material: 'bakery_dining' }, '🎟️': { ios: 'ticket.fill', material: 'confirmation_number' }, '🚙': { ios: 'car.fill', material: 'directions_car' }, '🧭': { ios: 'location.north.line.fill', material: 'explore' }, '📷': { ios: 'camera.fill', material: 'photo_camera' }, '📸': { ios: 'camera.fill', material: 'photo_camera' }, '🗺️': { ios: 'map.fill', material: 'map' },
  group: { ios: 'person.3.fill', material: 'groups' }, '🤝': { ios: 'person.3.fill', material: 'groups' }, '🧑‍🤝‍🧑': { ios: 'person.3.fill', material: 'groups' }, '🛡️': { ios: 'shield.lefthalf.filled', material: 'shield' }, '🔒': { ios: 'lock.fill', material: 'lock' }, '💸': { ios: 'banknote.fill', material: 'payments' }, '🧾': { ios: 'receipt.fill', material: 'receipt_long' }, '💡': { ios: 'lightbulb.fill', material: 'lightbulb' },
  journal: { ios: 'book.closed.fill', material: 'auto_stories' }, '💌': { ios: 'envelope.fill', material: 'mail' }, '📦': { ios: 'shippingbox.fill', material: 'inventory_2' },
  map: { ios: 'map.fill', material: 'map' }, search: { ios: 'magnifyingglass', material: 'search' }, settings: { ios: 'gearshape.fill', material: 'settings' }, '⚙': { ios: 'gearshape.fill', material: 'settings' },
  phone: { ios: 'iphone', material: 'smartphone' }, mail: { ios: 'envelope.fill', material: 'mail' }, apple: { ios: 'apple.logo', material: 'phone_iphone' }, share: { ios: 'square.and.arrow.up', material: 'share' }, arrow: { ios: 'arrow.right', material: 'arrow_forward' }, notifications: { ios: 'bell.fill', material: 'notifications' }, '♧': { ios: 'bell.fill', material: 'notifications' }, profile: { ios: 'person.crop.circle.fill', material: 'account_circle' }, '◉': { ios: 'person.crop.circle.fill', material: 'account_circle' }, heart: { ios: 'heart.fill', material: 'favorite' }, '♡': { ios: 'heart', material: 'favorite_border' }, '♙': { ios: 'person.fill', material: 'person' }, '⇄': { ios: 'arrow.left.arrow.right', material: 'compare_arrows' }, '◈': { ios: 'globe', material: 'language' }, '?': { ios: 'questionmark.circle', material: 'help' }, '▦': { ios: 'map', material: 'map' }, '▤': { ios: 'book.closed', material: 'menu_book' }, packing: { ios: 'checklist', material: 'checklist' },
  '♥': { ios: 'heart.fill', material: 'favorite' }, star: { ios: 'star.fill', material: 'star' }, '✦': { ios: 'sparkle', material: 'auto_awesome' }, '✳': { ios: 'sparkle', material: 'auto_awesome' },
  add: { ios: 'plus', material: 'add' }, '＋': { ios: 'plus', material: 'add' }, '＋ ': { ios: 'plus', material: 'add' }, back: { ios: 'chevron.left', material: 'arrow_back' }, next: { ios: 'chevron.right', material: 'arrow_forward' }, check: { ios: 'checkmark', material: 'check' }, '✓': { ios: 'checkmark', material: 'check' }, help: { ios: 'questionmark.circle.fill', material: 'help' }, clock: { ios: 'clock.fill', material: 'schedule' },
  '🌍': { ios: 'globe.americas.fill', material: 'public' }, '🌅': { ios: 'sunrise.fill', material: 'wb_sunny' }, '🍦': { ios: 'icecream.fill', material: 'icecream' }, '✈️': { ios: 'airplane', material: 'flight' }, '👋': { ios: 'hand.wave.fill', material: 'waving_hand' },
};

export function AppIcon({ name, size = 20, color = '#133B2C' }: { name: string; size?: number; color?: string }) {
  const icon = icons[name] ?? { ios: 'circle.fill', material: 'circle' };
  const symbolName = { ios: icon.ios as SFSymbol, android: icon.material as AndroidSymbol, web: icon.material as AndroidSymbol };
  return <View accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={[styles.frame, { width: size, height: size }]}><SymbolView name={symbolName} size={size} tintColor={color} weight="semibold" /></View>;
}
const styles = StyleSheet.create({ frame: { alignItems: 'center', justifyContent: 'center' } });
